# Generated by Django 5.2.13 on 2026-04-23 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubboard', '0006_club_slug_post_club_post_slug_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
