# Generated by Django 5.2.13 on 2026-05-01 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubboard', '0006_club_slug_post_club_post_slug_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='clubboard.post'),
        ),
    ]
