# Generated by Django 5.2.13 on 2026-04-23 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubboard', '0007_remove_club_slug_remove_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
