# Generated by Django 5.2.13 on 2026-05-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubboard', '0007_reply_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='days',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
