# Generated by Django 5.2.13 on 2026-05-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubboard', '0008_club_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='int_users',
            field=models.JSONField(null=True),
        ),
    ]
